# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d2bcb850163c576ddba6ebc3544d778f97ff6e2c3810c1fc5eb76d77a717135aed7e66f28b8802afb418c2c4e466e65b50aef2f13dd0adcb341c850784f1ecd

test:
  secret_key_base: ac3d7a5c3f9267c3fd29685190538bfa2f80d471f2db76cdc2718cc942358ee4a47945b08d23fff337e8582a86d3ba311d6b1ee758fd834e6161b29dadf6e79b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
